// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4kB21FhKvXUPcOVA3PZopYfSzWpcViGg',
    appId: '1:1039621189603:web:67793b2bff6ae203003ad6',
    messagingSenderId: '1039621189603',
    projectId: 'flutter-ai-playground-25a2b',
    authDomain: 'flutter-ai-playground-25a2b.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-25a2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMyK5zhNgcs9EdN0qkVRwI4QOrTaz16wk',
    appId: '1:1039621189603:android:2c8c030cc0ed0f9f003ad6',
    messagingSenderId: '1039621189603',
    projectId: 'flutter-ai-playground-25a2b',
    storageBucket: 'flutter-ai-playground-25a2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOAlN5ZOVdGGSz573G-KwNJ4W5DSbM5H4',
    appId: '1:1039621189603:ios:810c783f261cf4a1003ad6',
    messagingSenderId: '1039621189603',
    projectId: 'flutter-ai-playground-25a2b',
    storageBucket: 'flutter-ai-playground-25a2b.firebasestorage.app',
    iosBundleId: 'com.example.appDoAn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOAlN5ZOVdGGSz573G-KwNJ4W5DSbM5H4',
    appId: '1:1039621189603:ios:810c783f261cf4a1003ad6',
    messagingSenderId: '1039621189603',
    projectId: 'flutter-ai-playground-25a2b',
    storageBucket: 'flutter-ai-playground-25a2b.firebasestorage.app',
    iosBundleId: 'com.example.appDoAn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4kB21FhKvXUPcOVA3PZopYfSzWpcViGg',
    appId: '1:1039621189603:web:67793b2bff6ae203003ad6',
    messagingSenderId: '1039621189603',
    projectId: 'flutter-ai-playground-25a2b',
    authDomain: 'flutter-ai-playground-25a2b.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-25a2b.firebasestorage.app',
  );
}